services:
  - type: web
    name: maha-eseva-erp
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_NAME
        value: "Maha E-Seva ERP"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: APP_URL
        value: https://maha-eseva-erp.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
